### ISSUE TITLE
Unclear on monitor commands after boot

### ISSUE THREAD

**Issue by jcwren** [BigEd/a6502#1]
I've loaded the a6502.bin file into a Discovery board, and it enumerates on USB and outputs the following:

```
Hi
 00  00  00  00  00  00  00  00
Go:  fdd3

-
```

According to the docs, it's starting Supermon64, although based on some Googling, the Supermon64 prompt should be a '.'. I've tried various commands, with only 'g' and 'x' doing anything. I'm guessing that 'g' should be 'go', but don't know how to set the address. 'x' is dumping memory from 0x0000..0x007f.

Would it be possible to indicate what commands are supported, or a link? If it's running Supermon64, I did find [this](http://www.atarimagazines.com/compute/issue32/082_1_SUPERMON_64.php) article.

(I did see the link to Chris Baird's stm6502 project, but that link is now dead)

Thanks!

**Comment by BigEd** [comment]
It's been a while, let me see what I can remember or dig up!

As you are seeing a dash prompt, I think you must be running Bruce's C'Mon compact monitor. In other words, that must be the default content of the emulated 6502 if you take the prebuilt a6502.bin

See https://github.com/BigEd/a6502/blob/master/extras/cmon.a65
"It doesn't do much, but you can dump memory, write memory, and call routines (which, in theory, is all you need)"
- http://forum.6502.org/viewtopic.php?f=2&t=2046

So, four hex digits then a one letter command: "x" to examine memory, "g" to go (start execution) and if you want to load up a program, well, I'm not sure right now. It looks like there's an "@" command and a "," (comma) command.

It looks like the version of C'mon in a6502.bin does not include the monitor/single stepper - that's "$" - whereas the binary cmon.bin does include it.

We could try to figure out how to drive C'mon, or perhaps better would be to see if you can build a version of the emulator with the much larger multi-purpose image basfigmon.img instead - that has the monitor, forth, and basic all in one. Do you have the tools installed to allow you to run the Makefile, or the commands in it? Without intervention, the Makefile would do this:

`arm-none-eabi-gcc -mcpu=cortex-m4 -std=c99 -Os -g -Wall -Wextra -fno-common -mcpu=cortex-m4 -mthumb -msoft-float -MD -DSTM32F4 -DIMAGEFILE=extras/cmon.bin -DDEBUG -c a6502.c`
`arm-none-eabi-gcc -mcpu=cortex-m4 -std=c99 -Os -g -Wall -Wextra -fno-common -mcpu=cortex-m4 -mthumb -msoft-float -MD -DSTM32F4 -DIMAGEFILE=extras/cmon.bin -DDEBUG -c top.c`
`arm-none-eabi-gcc -mcpu=cortex-m4 -std=c99 -Os -g -Wall -Wextra -fno-common -mcpu=cortex-m4 -mthumb -msoft-float -MD -DSTM32F4 -DIMAGEFILE=extras/cmon.bin -DDEBUG -c emulator.S`
`arm-none-eabi-gcc -mcpu=cortex-m4 -std=c99 -Os -g -Wall -Wextra -fno-common -mcpu=cortex-m4 -mthumb -msoft-float -MD -DSTM32F4 -DIMAGEFILE=extras/cmon.bin -DDEBUG -c memimage.S`
`arm-none-eabi-gcc -o a6502.elf a6502.o top.o emulator.o memimage.o -lopencm3_stm32f4 -lc -lnosys -T./stm32f4-discovery.ld -nostartfiles -Wl,--gc-sections -mthumb -mcpu=cortex-m4 -march=armv7 -mfix-cortex-m3-ldrd -msoft-float`
`arm-none-eabi-objcopy -Obinary a6502.elf a6502.bin`
`echo now write to dev board with: st-flash write a6502.bin 0x08000000`

If you use that, I think you'll get a version of the monitor with single stepping. If you change all the instances of cmon.bin to basfigmon.img you'll get the all-in binary.

(I seem to have a copy of Chris' project at https://github.com/BigEd/stm6502)

**Comment by BigEd** [comment]
Ah, I found a mirror of the documentation for the Compact Monitor:
http://biged.github.io/6502-website-archives/lowkey.comuf.com/cmon.htm

**Comment by BigEd** [comment]
I've added a second courtesy binary to load on the discovery board: `extras/basfigmon.bin` which gives you supermon, forth and basic. It boots into supermon: instructions at
http://www.jbrain.com/pub/cbm/services/GEnie/Library%2022/supermon%20docs

And you can `g c800` to start EhBASIC, then `CALL -2048` to get back to the monitor.

**Comment by BigEd** [comment]
Hi @jcwren did you manage to get anywhere with this?

**Comment by jcwren** [comment]
Yes, in fact, I did, thank you. Not too long after I had posted the original question, I figured out that I hadn't included that. I now have the board up and running with the basfigmon binary. I didn't get back to posting anything here because I got distracted by shiny objects and this annoying thing called "work". I find it drastically interferes with my play time.
