### ISSUE TITLE
bug of macro do_ror_inner

### ISSUE THREAD

**Issue by PudgeMa** [BigEd/a6502#2]
this macro can't handle zero flag correctly now.
test case:
when cary flag is cleared and register value is 0x01,  it fails to set zero flag. 

fix code:

```
.macro do_ror_inner reg
        setflags_pre
        it cs
        orrcs   \reg, #0x100
        tst     \reg, #0x1
        it ne
        orrne   \reg, #0x200
        bic     \reg, #0x1          @ clear bit 1 !!!!!
        lsls	\reg, #23
        setflags_post
        lsr	\reg, #24
.endm
```

**Comment by BigEd** [comment]
Thanks for the report! I'm much less clever now than I was when I wrote this code. I'd quite like to know how Klaus' tests didn't find this.  Here's the code in context:
https://github.com/BigEd/a6502/blob/9691b6459ae6171c228c56e4cb440b7b104b4aa6/emulator.S#L824

**Comment by BigEd** [comment]
(Change not tested by me! But thanks for the report and the fix.)
